import Head from "next/head"
import { Rom } from "../types"
import { prisma } from "../prisma/db"
import { transformRom } from "./api/roms"
import { RomGrid } from "../components/rom-grid/RomGrid"
import styles from "../styles/Home.module.css"
import { useRomsFetcher } from "../components/useRomsFetcher"
import { RomGridPaginator } from "../components/rom-grid/RomGridPaginator"

export async function getServerSideProps() {
  const total = await prisma.rom.count()
  const roms = await prisma.rom.findMany({ take: 15 })

  return {
    props: {
      initialRoms: roms.map(transformRom),
      total,
    },
  }
}

type Props = {
  initialRoms: Rom[]
  total: number
}

export default function Home({ initialRoms, total }: Props) {
  const {
    roms,
    canFetchNext,
    canFetchPrev,
    nextPage,
    prevPage,
    currentPage,
    totalPages,
  } = useRomsFetcher(initialRoms, total)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <span>ROM</span>
        <img src="/assets/child-game-svgrepo-com.svg" alt="logo" />
        <span>HUB</span>
      </header>

      <main className={styles.main}>
        <RomGrid roms={roms || initialRoms} />
        <RomGridPaginator
          canFetchNext={canFetchNext}
          canFetchPrev={canFetchPrev}
          currentPage={currentPage}
          totalPages={totalPages}
          nextPage={nextPage}
          prevPage={prevPage}
        />
      </main>
    </div>
  )
}
